export const GET_ERRORS = 'GET_ERRORS';
export const HOME_AND_BUSINESS_LOGIN = 'HOME_AND_BUSINESS_LOGIN';
export const HOME_AND_BUSINESS_LOGIN_ERROR = 'HOME_AND_BUSINESS_LOGIN_ERROR';
export const TOP_UP = 'TOP_UP';
export const TOP_UP_ERROR = 'TOP_UP_ERROR';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const POST_FEEDBACK = 'POST_FEEDBACK';
export const FETCH_STATEMENTS = 'FETCH_STATEMENTS';
